### ISSUE TITLE
3rd Party log in and change password

### ISSUE THREAD

**Issue by taku-zw** [jsodeman/vue-core-jwt#2]
Can you add, 3rd Party log in such as google and Facebook and a change password option once user is authenticated

**Comment by jsodeman** [comment]
Auth0 https://auth0.com/ has extensive documentation and a SDK for implementing 3rd party login. They probably have a bootstrapping template like this for their service already.

Adding it into this might be better done in a fork of this project. I'm trying to keep this one generic enough that it can be modified for things like 3rd party and not have much extra code that needs to be ignored or deleted for projects that have different needs.
